sudo: required
dist: trusty
language: node_js
before_install:
  - sed -i 's/vm.vertebrae.io/localhost/g' config.sample.js
addons:
  postgresql: '9.6'
node_js:
  - '8.4.0'
git:
  depth: 3
notifications:
  slack: vertebrae-io:lernnSm4ESLg3QdUdfSU3unB
